name: bound_mutation
description: "A small wrapper class around Riverpod Mutations to bind a function to a mutation."
version: 1.0.2
repository: https://github.com/Cunibon/bound_mutation

environment:
  sdk: ^3.8.0

dependencies:
  riverpod: ^3.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
